/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#00478d',
        'primary-container': '#005eb8',
        'on-primary': '#ffffff',
        'on-primary-container': '#c8daff',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#a9c7ff',
        'inverse-primary': '#a9c7ff',
        secondary: '#332fe7',
        'secondary-container': '#4f50ff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#eceaff',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c0c1ff',
        tertiary: '#8d1900',
        'tertiary-container': '#b32c0e',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffcfc4',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#ffffff',
        'surface-dim': '#e0d9d1',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#faf2ea',
        'surface-container': '#f4ede5',
        'surface-container-high': '#efe7df',
        'surface-container-highest': '#e9e1d9',
        'surface-variant': '#e9e1d9',
        'surface-glass': 'rgba(255,255,255,0.75)',
        'on-surface': '#1e1b17',
        'on-surface-variant': '#424752',
        'inverse-surface': '#33302b',
        'inverse-on-surface': '#f7efe7',
        outline: '#727783',
        'outline-variant': '#c2c6d4',
        background: '#ffffff',
        'on-background': '#1e1b17',
        'medical-blue-muted': '#E6EFF8',
        'success-green': '#2D8A4E',
        'success-green-light': '#E8F5ED',
        'ink-dark': '#1C1C1C',
        'warm-surface': '#faf2ea',
      },
      fontFamily: {
        sans: ['Public Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['36px', { lineHeight: '44px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['16px', { lineHeight: '24px', fontWeight: '600', letterSpacing: '0.01em' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.01em' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.02em' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      maxWidth: {
        container: '1280px',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
      },
      boxShadow: {
        airy: '0px 4px 12px rgba(0, 94, 184, 0.06)',
        'airy-md': '0px 8px 24px rgba(0, 94, 184, 0.08)',
        'airy-lg': '0px 12px 32px rgba(0, 0, 0, 0.08)',
        'airy-xl': '0px 20px 48px rgba(0, 0, 0, 0.10)',
        card: '0px 2px 8px rgba(0,0,0,0.04), 0px 8px 24px rgba(0,94,184,0.06)',
      },
      backdropBlur: {
        glass: '20px',
      },
      animation: {
        'fade-up': 'fadeUp 0.6s ease-out forwards',
        'fade-in': 'fadeIn 0.4s ease-out forwards',
        pulse: 'pulse 2s cubic-bezier(0.4,0,0.6,1) infinite',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
