import Link from 'next/link'
import { AlertTriangle, Phone } from 'lucide-react'

export const metadata = { title: 'Medical Disclaimer — CareCompass' }

export default function DisclaimerPage() {
  return (
    <>
      <div className="bg-surface-container-low border-b border-outline-variant/30 pt-28 pb-12">
        <div className="section-container">
          <p className="text-label-md text-primary uppercase tracking-widest mb-2">Legal</p>
          <h1 className="text-display-md text-ink-dark">Medical Disclaimer</h1>
          <p className="text-body-lg text-on-surface-variant mt-3 max-w-2xl">
            CareCompass is a technology platform, not a medical provider. Please read this disclaimer carefully.
          </p>
        </div>
      </div>

      <div className="section-container py-14 max-w-3xl space-y-10">
        {/* Emergency callout */}
        <div className="bg-error-container rounded-2xl p-6 flex gap-4">
          <AlertTriangle size={24} className="text-error flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-error font-bold text-body-md mb-1">If you have a medical emergency, call 999 immediately.</p>
            <p className="text-on-error-container text-body-sm leading-relaxed">
              Do not use CareCompass or wait for AI triage in a life-threatening situation. Signs of emergency include: chest pain, difficulty breathing, severe bleeding, loss of consciousness, stroke symptoms, or severe allergic reaction.
            </p>
            <a href="tel:999" className="inline-flex items-center gap-2 mt-3 bg-error text-white px-5 py-2.5 rounded-full font-bold text-label-md hover:bg-red-700 transition-colors">
              <Phone size={14} /> Call 999
            </a>
          </div>
        </div>

        <section>
          <h2 className="text-headline-md text-ink-dark mb-4">Not Medical Advice</h2>
          <p className="text-body-md text-on-surface-variant leading-relaxed mb-3">
            The information, recommendations, and triage guidance provided by CareCompass — whether generated by our AI engine or curated by our clinical team — is for general informational and educational purposes only.
          </p>
          <p className="text-body-md text-on-surface-variant leading-relaxed">
            It does not constitute medical advice, diagnosis, or treatment. Always seek the advice of a qualified health provider with any questions you may have regarding a medical condition.
          </p>
        </section>

        <section>
          <h2 className="text-headline-md text-ink-dark mb-4">No Doctor–Patient Relationship</h2>
          <p className="text-body-md text-on-surface-variant leading-relaxed">
            Use of CareCompass does not create a doctor–patient or therapist–patient relationship between you and CareCompass or any of its clinical reviewers. The triage output is a navigational aid, not a clinical assessment by a licensed practitioner who has examined you.
          </p>
        </section>

        <section>
          <h2 className="text-headline-md text-ink-dark mb-4">Limitations of AI Triage</h2>
          <p className="text-body-md text-on-surface-variant leading-relaxed mb-3">
            Our AI models are trained on medical literature and reviewed by clinicians, but they have inherent limitations:
          </p>
          <ul className="space-y-2">
            {[
              'AI cannot physically examine you or observe vital signs.',
              'Symptom descriptions vary and may be interpreted differently by an AI than by a trained clinician.',
              'Rare or atypical disease presentations may not be captured accurately.',
              'The system does not account for your full medical history unless you provide it.',
            ].map((item) => (
              <li key={item} className="flex gap-3 text-body-md text-on-surface-variant">
                <span className="w-1.5 h-1.5 rounded-full bg-primary mt-2.5 flex-shrink-0" />
                {item}
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-headline-md text-ink-dark mb-4">Clinic Information</h2>
          <p className="text-body-md text-on-surface-variant leading-relaxed">
            Facility details, wait times, and availability shown on CareCompass are provided by partner clinics and may not always reflect real-time conditions. CareCompass does not guarantee the availability of services, the accuracy of wait times, or the clinical quality of any listed facility.
          </p>
        </section>

        <section>
          <h2 className="text-headline-md text-ink-dark mb-4">Your Responsibility</h2>
          <p className="text-body-md text-on-surface-variant leading-relaxed">
            You are solely responsible for decisions you make based on information from CareCompass. Never disregard or delay professional medical advice because of something you read or received from our platform.
          </p>
        </section>

        <div className="pt-8 border-t border-outline-variant/30 flex flex-wrap gap-4">
          <Link href="/terms" className="text-primary text-label-md font-semibold hover:underline">Terms of Service →</Link>
          <Link href="/privacy" className="text-primary text-label-md font-semibold hover:underline">Privacy Policy →</Link>
          <Link href="/emergency" className="text-primary text-label-md font-semibold hover:underline">Emergency Info →</Link>
        </div>
      </div>
    </>
  )
}
