import type { Clinic, AdminStats, SymptomCheck } from '@/types'

export const PLACEHOLDER_CLINICS: Clinic[] = [
  {
    id: '1',
    name: 'Aga Khan University Hospital',
    type: 'hospital',
    address: '3rd Parklands Avenue, Nairobi',
    area: 'Parklands',
    distance: '1.2 km',
    waitMinutes: 20,
    isOpen: true,
    hours: '24 hours',
    phone: '+254 20 366 2000',
    whatsapp: '+254 720 000 001',
    services: ['Emergency', 'Radiology', 'ICU', 'Pharmacy', 'Laboratory'],
    acceptsUninsured: true,
    costRange: 'high',
    rating: 4.8,
    reviewCount: 1240,
    coordinates: { lat: -1.2636, lng: 36.8116 },
    verified: true,
  },
  {
    id: '2',
    name: 'Nairobi Hospital',
    type: 'hospital',
    address: 'Argwings Kodhek Road, Nairobi',
    area: 'Upperhill',
    distance: '2.8 km',
    waitMinutes: 45,
    isOpen: true,
    hours: '24 hours',
    phone: '+254 20 284 5000',
    whatsapp: '+254 720 000 002',
    services: ['Emergency', 'Surgery', 'Maternity', 'Oncology', 'Pharmacy'],
    acceptsUninsured: true,
    costRange: 'high',
    rating: 4.6,
    reviewCount: 980,
    coordinates: { lat: -1.2975, lng: 36.8157 },
    verified: true,
  },
  {
    id: '3',
    name: 'City Park Medical Clinic',
    type: 'clinic',
    address: 'Forest Road, Nairobi',
    area: 'Parklands',
    distance: '0.8 km',
    waitMinutes: 10,
    isOpen: true,
    hours: 'Mon–Sat 7am–9pm',
    phone: '+254 20 000 1234',
    whatsapp: '+254 720 000 003',
    services: ['General Practice', 'Laboratory', 'Pharmacy', 'Vaccination'],
    acceptsUninsured: true,
    costRange: 'low',
    rating: 4.4,
    reviewCount: 312,
    coordinates: { lat: -1.2601, lng: 36.8219 },
    verified: true,
  },
  {
    id: '4',
    name: 'Westlands Urgent Care',
    type: 'urgent-care',
    address: 'Waiyaki Way, Westlands',
    area: 'Westlands',
    distance: '3.5 km',
    waitMinutes: 15,
    isOpen: true,
    hours: 'Daily 8am–10pm',
    phone: '+254 20 000 5678',
    whatsapp: '+254 720 000 004',
    services: ['Urgent Care', 'X-Ray', 'Laboratory', 'Wound Care'],
    acceptsUninsured: true,
    costRange: 'moderate',
    rating: 4.3,
    reviewCount: 187,
    coordinates: { lat: -1.2676, lng: 36.8029 },
    verified: true,
  },
  {
    id: '5',
    name: 'Mpango wa Jamii Community Clinic',
    type: 'clinic',
    address: 'Ngara Road, Ngara',
    area: 'Ngara',
    distance: '4.1 km',
    waitMinutes: 30,
    isOpen: false,
    hours: 'Mon–Fri 8am–5pm',
    phone: '+254 20 000 9012',
    services: ['General Practice', 'Maternal Health', 'HIV Testing', 'Vaccination'],
    acceptsUninsured: true,
    costRange: 'free',
    rating: 4.1,
    reviewCount: 89,
    coordinates: { lat: -1.2782, lng: 36.8327 },
    verified: true,
  },
  {
    id: '6',
    name: 'QuickCare Pharmacy & Clinic',
    type: 'pharmacy',
    address: 'Tom Mboya Street, CBD',
    area: 'CBD',
    distance: '5.2 km',
    waitMinutes: 5,
    isOpen: true,
    hours: 'Daily 7am–11pm',
    phone: '+254 20 000 3456',
    services: ['Pharmacy', 'Basic Consultation', 'Blood Pressure', 'Diabetes Screening'],
    acceptsUninsured: true,
    costRange: 'low',
    rating: 3.9,
    reviewCount: 204,
    coordinates: { lat: -1.2835, lng: 36.8216 },
    verified: false,
  },
]

export const SYMPTOM_SUGGESTIONS = [
  'Chest pain',
  'Difficulty breathing',
  'Severe headache',
  'High fever',
  'Abdominal pain',
  'Dizziness or fainting',
  'Persistent cough',
  'Sore throat',
  'Skin rash',
  'Joint pain',
  'Nausea or vomiting',
  'Back pain',
  'Eye redness',
  'Toothache',
  'Fatigue',
]

export const PLACEHOLDER_HISTORY: SymptomCheck[] = [
  {
    id: 'h1',
    date: '2024-06-01',
    symptoms: ['Sore throat', 'Mild fever'],
    urgency: 'routine',
    summary: 'Likely upper respiratory infection',
    recommendation: 'Rest, fluids, and over-the-counter remedies. See a doctor if symptoms persist beyond 5 days.',
  },
  {
    id: 'h2',
    date: '2024-05-18',
    symptoms: ['Chest pain', 'Shortness of breath'],
    urgency: 'emergency',
    summary: 'Symptoms consistent with cardiac event',
    recommendation: 'Immediately seek emergency care. Do not drive yourself.',
  },
]

export const ADMIN_STATS: AdminStats = {
  totalChecks: 15842,
  checksToday: 312,
  emergencyRate: 8.4,
  urgentRate: 31.2,
  routineRate: 60.4,
  avgResponseTime: 12,
  activeClinics: 248,
  newUsersThisWeek: 1240,
}

export const TOP_SYMPTOMS_TODAY = [
  { symptom: 'Fever', count: 94 },
  { symptom: 'Cough', count: 76 },
  { symptom: 'Headache', count: 61 },
  { symptom: 'Abdominal pain', count: 48 },
  { symptom: 'Chest pain', count: 29 },
  { symptom: 'Rash', count: 22 },
]

export const COST_LABELS: Record<string, string> = {
  free: 'Free / NHIF',
  low: 'Under KES 1,000',
  moderate: 'KES 1,000–5,000',
  high: 'KES 5,000+',
}
